version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-ai-lab
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # These variables configure n8n's internal settings
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Africa/Tunis
    volumes:
      # This links our local folder to the container's data folder
      - ./n8n_data:/home/node/.n8n
  postgres:
    image: postgres:16-alpine
    container_name: n8n-lab-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n_chat_history
    ports:
      - "5433:5432" # Mapping to 5433 to avoid conflict with other DB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
